#!/usr/bin/env python
"""Create the required two-page report.pdf after training and evaluation."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a compact assignment report PDF.")
    parser.add_argument("--out", type=Path, default=Path("report.pdf"))
    parser.add_argument("--samples_dir", type=Path, default=Path("samples"))
    parser.add_argument("--weights", type=Path, default=Path("lora_out/pytorch_lora_weights.safetensors"))
    parser.add_argument("--team", default="")
    parser.add_argument("--prompt", default="a busy market, in <sks> style")
    parser.add_argument("--model_name", default="runwayml/stable-diffusion-v1-5")
    parser.add_argument("--data_dir", default="style_imgs/512")
    parser.add_argument("--instance_token", default="<sks>")
    parser.add_argument("--rank", type=int, default=16)
    parser.add_argument("--text_encoder_rank", type=int, default=4)
    parser.add_argument("--unet_learning_rate", default="7e-5")
    parser.add_argument("--text_encoder_learning_rate", default="2.5e-6")
    parser.add_argument("--token_learning_rate", default="1e-5")
    parser.add_argument("--selected_step", type=int, default=250)
    return parser.parse_args()


def draw_wrapped(c: canvas.Canvas, text: str, x: float, y: float, max_chars: int, leading: float = 12) -> float:
    words = text.split()
    line = ""
    for word in words:
        candidate = f"{line} {word}".strip()
        if len(candidate) > max_chars and line:
            c.drawString(x, y, line)
            y -= leading
            line = word
        else:
            line = candidate
    if line:
        c.drawString(x, y, line)
        y -= leading
    return y


def draw_bullets(c: canvas.Canvas, items: list[str], x: float, y: float, max_chars: int) -> float:
    for item in items:
        c.drawString(x, y, "-")
        y = draw_wrapped(c, item, x + 12, y, max_chars=max_chars)
        y -= 2
    return y


def find_samples(samples_dir: Path) -> list[Path]:
    patterns = ["adapter_*.png", "*.png", "*.jpg", "*.jpeg"]
    samples: list[Path] = []
    for pattern in patterns:
        samples.extend(sorted(samples_dir.glob(pattern)))
        if len(samples) >= 6:
            break
    return samples[:6]


def draw_image_fit(c: canvas.Canvas, path: Path, x: float, y: float, max_w: float, max_h: float) -> None:
    with Image.open(path) as image:
        width, height = image.size
    scale = min(max_w / width, max_h / height)
    draw_w = width * scale
    draw_h = height * scale
    c.drawImage(str(path), x + (max_w - draw_w) / 2, y + (max_h - draw_h) / 2, draw_w, draw_h)


def main() -> None:
    args = parse_args()
    args.out.parent.mkdir(parents=True, exist_ok=True)

    page_w, page_h = A4
    margin = 2 * cm
    c = canvas.Canvas(str(args.out), pagesize=A4)

    c.setTitle("Ghibli Market: LoRA Style-Tuning with Stable Diffusion 1.5")
    c.setFont("Helvetica-Bold", 18)
    c.drawString(margin, page_h - margin, "Ghibli Market: LoRA Style-Tuning")

    y = page_h - margin - 26
    c.setFont("Helvetica", 10)
    if args.team:
        y = draw_wrapped(c, f"Team members: {args.team}", margin, y, 95)

    c.setFont("Helvetica-Bold", 13)
    c.drawString(margin, y - 14, "Objective")
    c.setFont("Helvetica", 10)
    y = draw_wrapped(
        c,
        f"We fine-tuned {args.model_name} so that the new token {args.instance_token} represents the visual style of the supplied image collection. Our target was to generate a detailed, populated market from the prompt: {args.prompt}.",
        margin,
        y - 34,
        max_chars=96,
    )

    c.setFont("Helvetica-Bold", 13)
    c.drawString(margin, y - 10, "Final training approach")
    c.setFont("Helvetica", 10)
    y = draw_bullets(
        c,
        [
            f"We added {args.instance_token} to the tokenizer, initialized it from the phrase 'ghibli style', and trained its embedding together with LoRA adapters on both the UNet and CLIP text encoder.",
            "The main dataset contained all 843 supplied 512x512 images. Florence-2 captions were converted to prompts ending in 'in <sks> style', with 8% generic-caption dropout.",
            "We added 60 images generated by the unmodified SD 1.5 model: broad market views, market scenes with visible people, and people or portrait scenes. These examples helped preserve the base model's knowledge of markets and human figures while the supplied images determined the style.",
            "The loss combined Min-SNR-weighted diffusion training with a base-model preservation term and a small anchor on the learned token embedding.",
            f"Training used 512x512 crops, UNet rank {args.rank}, text-encoder rank {args.text_encoder_rank}, fp16, batch size 1 with four-step accumulation, random crops and flips, and a cosine learning-rate schedule. We selected checkpoint {args.selected_step}.",
        ],
        margin,
        y - 28,
        max_chars=91,
    )

    c.setFont("Helvetica-Bold", 13)
    c.drawString(margin, y - 10, "Experiments and observed impact")
    c.setFont("Helvetica", 10)
    y = draw_bullets(
        c,
        [
            "Supplied images only: style transfer was already strong, while market layouts remained relatively simple and flat.",
            "Base-model market examples: stalls became more structured, groups of people separated more clearly, and the target prompt produced populated scenes more reliably. This became the main training recipe.",
            "Face and person crop emphasis: an 8% crop share improved close portraits and larger faces. Its effect was concentrated at portrait scale, so the final mix kept a lighter emphasis on people instead of making crops dominant.",
            "Longer cosine training: market composition and local detail continued to improve until approximately step 250. Later checkpoints changed only slightly, so step 250 was selected for the final adapter.",
            "Stronger preservation and lower learning rates: this kept scene layouts stable, while the original cosine run gave the most consistent balance between the learned style and market detail.",
        ],
        margin,
        y - 28,
        max_chars=91,
    )

    c.setFont("Helvetica-Bold", 13)
    c.drawString(margin, y - 8, "Final configuration")
    c.setFont("Helvetica", 10)
    draw_wrapped(
        c,
        f"Learning rates were {args.unet_learning_rate} for the UNet LoRA, {args.text_encoder_learning_rate} for the text-encoder LoRA, and {args.token_learning_rate} for the token embedding. We used LoRA dropout 0.05, Min-SNR gamma 5, preservation weight 0.65, token-anchor weight 0.05, 50 warmup steps, and seed 2202.",
        margin,
        y - 28,
        max_chars=96,
    )

    c.setFont("Helvetica", 8)
    c.drawCentredString(page_w / 2, 0.8 * cm, "Page 1 of 2")
    c.showPage()
    c.setFont("Helvetica-Bold", 16)
    c.drawString(margin, page_h - margin, "Results")
    c.setFont("Helvetica", 10)
    c.drawString(margin, page_h - margin - 18, f"Prompt: {args.prompt}")
    c.drawString(margin, page_h - margin - 32, "Inference: DPM-Solver++, 150 steps, CFG 7.5, 512x512, seeds 84000-84005")

    samples = find_samples(args.samples_dir)
    if samples:
        gap = 0.7 * cm
        box_w = (page_w - 2 * margin - 2 * gap) / 3
        box_h = box_w
        top = page_h - margin - 60
        for index, sample in enumerate(samples):
            column = index % 3
            row = index // 3
            x = margin + column * (box_w + gap)
            y_img = top - box_h - row * (box_h + 1.2 * cm)
            c.rect(x, y_img, box_w, box_h)
            draw_image_fit(c, sample, x, y_img, box_w, box_h)
            c.drawString(x, y_img - 14, f"Seed {84000 + index}")

        text_y = top - 2 * (box_h + 1.2 * cm) - 4
        c.setFont("Helvetica-Bold", 13)
        c.drawString(margin, text_y, "Qualitative result")
        c.setFont("Helvetica", 10)
        text_y = draw_wrapped(
            c,
            "The selected model consistently produced full market scenes with layered stalls, visible produce, crowds, and the warm hand-drawn appearance of the supplied references. The preservation examples helped retain readable market structure while <sks> controlled the style.",
            margin,
            text_y - 20,
            max_chars=96,
        )
        draw_wrapped(
            c,
            "For the final samples, increasing inference from 40 to 150 steps added shadow depth and clearer separation between foreground figures and background stalls. Changes beyond 150 steps were minimal, so 150 steps was used for the submitted images.",
            margin,
            text_y - 6,
            max_chars=96,
        )
    else:
        c.drawString(margin, page_h - margin - 52, "No generated samples found. Run code/eval_lora.py first.")

    c.setFont("Helvetica", 8)
    c.drawCentredString(page_w / 2, 0.8 * cm, "Page 2 of 2")
    c.save()
    print(f"Saved {args.out}")


if __name__ == "__main__":
    main()
