#!/usr/bin/env python
"""Validate image/caption metadata before LoRA training."""

from __future__ import annotations

import argparse
import hashlib
import json
from collections import Counter
from pathlib import Path


SUPPORTED_EXTENSIONS = {".bmp", ".jpeg", ".jpg", ".png", ".webp"}
FORBIDDEN_HASHES = {
    "6d9c85bd4b7950e5f660dbab2ff0d11c7a7524b58efa714a029d24cb79d6970d",
    "2fd8f10d6406514d27b8f4079ae2c87228e8db28afa3e42ee92c9a8c7bf25",
    "fc17c486f24c47c93f726a2dd8673096b25ecd5acd5e51229c8bdfb5922f34b6",
}
BASE_MODEL = "runwayml/stable-diffusion-v1-5"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Verify image folder and optional Florence captions JSONL.")
    parser.add_argument("--data_dir", type=Path, required=True)
    parser.add_argument("--captions_jsonl", type=Path, default=None)
    parser.add_argument("--auxiliary_jsonl", type=Path, default=None)
    parser.add_argument("--instance_token", default="<sks>")
    return parser.parse_args()


def resolve_caption_image_path(captions_path: Path, image_value: str) -> Path:
    image_path = Path(image_value)
    if image_path.is_absolute():
        return image_path.resolve()
    return (captions_path.parent / image_path).resolve()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def verify_auxiliary(path: Path) -> None:
    required = {
        "image",
        "caption",
        "source_kind",
        "sampling_weight",
        "target_prompt_prob",
        "sha256",
        "model",
        "generation_prompt",
        "negative_prompt",
        "seed",
        "scheduler",
        "num_inference_steps",
        "guidance_scale",
        "source_adapter_sha256",
    }
    rows = []
    seen = set()
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, 1):
            if not line.strip():
                continue
            row = json.loads(line)
            missing = required - set(row)
            if missing:
                raise ValueError(f"{path}:{line_number} missing {sorted(missing)}")
            image = resolve_caption_image_path(path, row["image"])
            if not image.is_file() or image.suffix.lower() not in SUPPORTED_EXTENSIONS:
                raise FileNotFoundError(image)
            digest = sha256(image)
            lowered = image.as_posix().lower()
            if "market_refs" in lowered or "pdf" in lowered or digest in FORBIDDEN_HASHES:
                raise ValueError(f"Forbidden auxiliary image: {image}")
            if digest != row["sha256"]:
                raise ValueError(f"Hash mismatch: {image}")
            if row["model"] != BASE_MODEL or row["source_adapter_sha256"] is not None:
                raise ValueError(f"Auxiliary image was not generated by unmodified SD 1.5: {image}")
            if not str(row["caption"]).strip() or not str(row["generation_prompt"]).strip():
                raise ValueError(f"Empty auxiliary prompt or caption: {image}")
            if float(row["sampling_weight"]) <= 0:
                raise ValueError(f"Invalid sampling weight: {image}")
            if not 0 <= float(row["target_prompt_prob"]) <= 1:
                raise ValueError(f"Invalid target prompt probability: {image}")
            if int(row["num_inference_steps"]) <= 0 or float(row["guidance_scale"]) <= 0:
                raise ValueError(f"Invalid generation settings: {image}")
            if image in seen:
                raise ValueError(f"Duplicate auxiliary image: {image}")
            seen.add(image)
            rows.append(row)
    if not rows:
        raise ValueError(f"No auxiliary rows found in {path}")
    print(f"Auxiliary rows: {len(rows)}")
    print(f"Auxiliary source kinds: {dict(Counter(row['source_kind'] for row in rows))}")


def main() -> None:
    args = parse_args()
    image_paths = sorted(
        path.resolve()
        for path in args.data_dir.rglob("*")
        if path.is_file() and path.suffix.lower() in SUPPORTED_EXTENSIONS
    )
    if not image_paths:
        raise ValueError(f"No supported images found in {args.data_dir}")

    print(f"Images: {len(image_paths)}")
    if args.captions_jsonl is None:
        raise ValueError("--captions_jsonl is required")

    rows = []
    caption_paths = []
    token_counts = Counter()
    with args.captions_jsonl.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, 1):
            if not line.strip():
                continue
            row = json.loads(line)
            image = resolve_caption_image_path(args.captions_jsonl, row["image"])
            caption = str(row.get("caption") or "").strip()
            prompt = str(row.get("prompt") or f"{caption}, in {args.instance_token} style")
            if not caption:
                raise ValueError(f"{args.captions_jsonl}:{line_number} has an empty caption")
            token_counts[prompt.count(args.instance_token)] += 1
            rows.append(row)
            caption_paths.append(image)

    if len(rows) != len(image_paths):
        raise ValueError(f"Expected {len(image_paths)} caption rows, found {len(rows)}")

    image_set = set(image_paths)
    caption_set = set(caption_paths)
    if image_set != caption_set:
        missing = sorted(image_set - caption_set)
        extra = sorted(caption_set - image_set)
        raise ValueError(f"Caption/image mismatch. Missing={len(missing)} Extra={len(extra)}")

    missing_files = [path for path in caption_paths if not path.exists()]
    if missing_files:
        raise ValueError(f"{len(missing_files)} caption image paths do not exist")

    if token_counts != Counter({1: len(rows)}):
        raise ValueError(f"Each prompt must contain exactly one {args.instance_token}; observed {dict(token_counts)}")

    print(f"Caption rows: {len(rows)}")
    print(f"Prompt token counts: {dict(token_counts)}")
    if args.auxiliary_jsonl is not None:
        verify_auxiliary(args.auxiliary_jsonl)
    print("Training data verification passed.")


if __name__ == "__main__":
    main()
